### ISSUE TITLE
Text overflow of log messages

### ISSUE THREAD

**Issue by an-dev** [darugnaa/kura-web-log#3]
Some of the log messages are overflowing the `<pre>` tag.
Perhaps it would be better to use a `<textarea>` with a larger width, or use javascript to dinamically increase the width based on the longer string appended.
![weblog_-_2016-01-09_20 20 26](https://cloud.githubusercontent.com/assets/5052825/12217892/f72b4464-b70e-11e5-98d3-3392b9a32807.png)

**Comment by darugnaa** [comment]
Thank you for reporting the issue. I'll merge the pull request ASAP.

**Comment by darugnaa** [comment]
I fixed this issue by adding an horizontal scrollbar. @an-dev could you please confirm that it works?

**Comment by an-dev** [comment]
Tested on 
Mac OSX and Ubuntu Linux 12.04 running 
Firefox 43
Chromium 49

Everything's ok.
