### ISSUE TITLE
"Hard coded" jar version

### ISSUE THREAD

**Issue by an-dev** [darugnaa/kura-web-log#4]
In /kura-web-log/distrib/build_dp.xml line 19 there's an old version of kura.weblog.jar which prevents build the deployment package.
This is an easy fix but it would be fit to consider passing the release number in someway or another.

**Comment by an-dev** [comment]
Fixed in https://github.com/darugnaa/kura-web-log/pull/5

**Comment by an-dev** [comment]
Fixed in https://github.com/darugnaa/kura-web-log/pull/6

**Comment by darugnaa** [comment]
Thanks for the fix. I was thinking about using some version file to read versions in, but to keep it simple I prefer to just write them in the ant file.
